apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aswarm-blue-api-auth-external
  namespace: aswarm-prod
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aswarm-secretstore
    kind: SecretStore
  target:
    name: aswarm-blue-api-auth
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: aswarm-blue-api
  data:
    - secretKey: auth-tokens
      remoteRef:
        key: aswarm-blue-api-auth
        property: auth-tokens