# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import federator_pb2 as federator__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in federator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FederatorStub(object):
    """Core federation service for secure cross-cluster communication
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ShareSketch = channel.unary_unary(
                '/aswarm.federation.Federator/ShareSketch',
                request_serializer=federator__pb2.ShareSketchRequest.SerializeToString,
                response_deserializer=federator__pb2.ShareSketchResponse.FromString,
                _registered_method=True)
        self.RequestSketch = channel.unary_unary(
                '/aswarm.federation.Federator/RequestSketch',
                request_serializer=federator__pb2.RequestSketchRequest.SerializeToString,
                response_deserializer=federator__pb2.RequestSketchResponse.FromString,
                _registered_method=True)
        self.ReportHealth = channel.unary_unary(
                '/aswarm.federation.Federator/ReportHealth',
                request_serializer=federator__pb2.HealthReportRequest.SerializeToString,
                response_deserializer=federator__pb2.HealthReportResponse.FromString,
                _registered_method=True)
        self.FederationStream = channel.stream_stream(
                '/aswarm.federation.Federator/FederationStream',
                request_serializer=federator__pb2.FederationMessage.SerializeToString,
                response_deserializer=federator__pb2.FederationMessage.FromString,
                _registered_method=True)


class FederatorServicer(object):
    """Core federation service for secure cross-cluster communication
    """

    def ShareSketch(self, request, context):
        """Share HLL sketch with Byzantine verification
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestSketch(self, request, context):
        """Request sketch from peer with attestation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportHealth(self, request, context):
        """Report cluster health and capability
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FederationStream(self, request_iterator, context):
        """Bidirectional stream for real-time federation updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ShareSketch': grpc.unary_unary_rpc_method_handler(
                    servicer.ShareSketch,
                    request_deserializer=federator__pb2.ShareSketchRequest.FromString,
                    response_serializer=federator__pb2.ShareSketchResponse.SerializeToString,
            ),
            'RequestSketch': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestSketch,
                    request_deserializer=federator__pb2.RequestSketchRequest.FromString,
                    response_serializer=federator__pb2.RequestSketchResponse.SerializeToString,
            ),
            'ReportHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportHealth,
                    request_deserializer=federator__pb2.HealthReportRequest.FromString,
                    response_serializer=federator__pb2.HealthReportResponse.SerializeToString,
            ),
            'FederationStream': grpc.stream_stream_rpc_method_handler(
                    servicer.FederationStream,
                    request_deserializer=federator__pb2.FederationMessage.FromString,
                    response_serializer=federator__pb2.FederationMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aswarm.federation.Federator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aswarm.federation.Federator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Federator(object):
    """Core federation service for secure cross-cluster communication
    """

    @staticmethod
    def ShareSketch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aswarm.federation.Federator/ShareSketch',
            federator__pb2.ShareSketchRequest.SerializeToString,
            federator__pb2.ShareSketchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestSketch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aswarm.federation.Federator/RequestSketch',
            federator__pb2.RequestSketchRequest.SerializeToString,
            federator__pb2.RequestSketchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aswarm.federation.Federator/ReportHealth',
            federator__pb2.HealthReportRequest.SerializeToString,
            federator__pb2.HealthReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FederationStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/aswarm.federation.Federator/FederationStream',
            federator__pb2.FederationMessage.SerializeToString,
            federator__pb2.FederationMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
