apiVersion: v1
kind: ConfigMap
metadata:
  name: aswarm-policy
  namespace: aswarm
data:
  policy_catalog.yaml: |
    policies:
      # Ring 1: Observable (no containment)
      - id: log-anomaly-default
        ring: 1
        action: log_anomaly
        params:
          anomaly_type: "network_scan"
        conditions:
          min_score: 0.6
          max_score: 0.7
      
      # Ring 2: Reversible network isolation
      - id: quarantine-vlan
        ring: 2
        action: networkpolicy_isolate
        params:
          ttl_seconds: 120
        conditions:
          min_score: 0.7
          max_score: 0.85
      
      - id: egress-throttle
        ring: 2
        action: egress_rate_limit
        params:
          rate_mbps: 10
          ttl_seconds: 300
        conditions:
          min_score: 0.75
          anomaly_type: "data_exfiltration"
      
      - id: dns-redirect
        ring: 2
        action: dns_sinkhole
        params:
          sinkhole_ip: "10.0.0.254"
          ttl_seconds: 600
        conditions:
          min_score: 0.8
          anomaly_type: "dns_tunneling"
      
      # Ring 3: Disruptive (requires higher scores)
      - id: token-suspend
        ring: 3
        action: token_revoke
        params:
          provider: "okta"
          scope: "refresh_tokens"
          ttl_seconds: 3600
        conditions:
          min_score: 0.85
          anomaly_type: "credential_compromise"
      
      - id: container-freeze
        ring: 3
        action: container_pause
        params:
          ttl_seconds: 180
        conditions:
          min_score: 0.9
          
    # Global settings
    settings:
      max_ring: 3  # Don't execute beyond Ring 3
      default_ttl: 300
      probe_interval: 30
      dry_run: true  # Set to false in production