apiVersion: batch/v1
kind: Job
metadata:
  name: quarantine-revert
  namespace: aswarm
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: aswarm-sa
      containers:
      - name: revert
        image: bitnami/kubectl:latest
        command: ["/bin/sh","-c"]
        args:
          - |
            # Read TTL from policy configmap
            TTL_SECONDS=$(kubectl -n aswarm get cm aswarm-policy -o jsonpath='{.data.policy_catalog\.yaml}' | grep ttl_seconds | awk '{print $2}')
            TTL_SECONDS=${TTL_SECONDS:-120}  # Default to 120s if not found
            
            echo "[A-SWARM] Auto-revert scheduled in ${TTL_SECONDS} seconds..."
            sleep ${TTL_SECONDS}
            
            # Remove quarantine label from all pods
            echo "[A-SWARM] Reverting quarantine..."
            kubectl -n aswarm label pods -l aswarm/quarantine=true aswarm/quarantine-
            
            # Log the revert action
            REVERT_TIME=$(date -u +%Y-%m-%dT%H:%M:%SZ)
            kubectl -n aswarm create cm aswarm-revert-log-${REVERT_TIME//[:-]/} \
              --from-literal=action=quarantine-revert \
              --from-literal=timestamp=${REVERT_TIME} \
              --from-literal=ttl_seconds=${TTL_SECONDS} || true
            
            echo "[A-SWARM] Quarantine reverted at ${REVERT_TIME}"